# Generated by Django 4.2 on 2023-04-12 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefone',
            name='padrao',
            field=models.BooleanField(default=False),
        ),
    ]
